[package]
name = "kirie-web"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
cef = ["dep:cef", "dep:cef-dll-sys", "dep:memmap2", "dep:tracing-subscriber", "dep:libc", "host"]
host = []
webview = ["dep:libloading", "dep:gtk", "dep:gtk-layer-shell", "dep:tracing-subscriber"]
webview-client = []

[dependencies]
blake3 = { workspace = true }
memmap2 = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
kirie-bake = { path = "../kirie-bake" }
kirie-platform = { path = "../kirie-platform" }
thiserror = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
arc-swap = { workspace = true }

cef = { version = "149", default-features = false, optional = true }
cef-dll-sys = { workspace = true, optional = true }

libloading = { version = "0.8", optional = true }
gtk = { workspace = true, optional = true }
gtk-layer-shell = { workspace = true, optional = true }

[[bin]]
name = "kirie-cef-helper"
path = "src/bin/kirie-cef-helper.rs"
required-features = ["cef"]

[dev-dependencies]
image = { workspace = true }

[[bin]]
name = "kirie-webhost"
path = "src/bin/kirie-webhost.rs"
required-features = ["cef"]

[[bin]]
name = "kirie-webviewhost"
path = "src/bin/kirie-webviewhost.rs"
required-features = ["webview"]
