[package]
name = "kirie-web"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
cef = ["dep:cef", "dep:cef-dll-sys", "dep:memmap2", "dep:tracing-subscriber", "dep:libc", "host"]
host = []
webview = ["dep:libloading", "dep:gtk", "dep:gtk-layer-shell", "dep:tracing-subscriber"]
webview-client = []
webview-mac = ["dep:objc2", "dep:objc2-app-kit", "dep:objc2-foundation", "dep:objc2-web-kit", "dep:block2"]

[dependencies]
blake3 = { workspace = true }
memmap2 = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
kirie-bake = { path = "../kirie-bake" }
kirie-platform = { path = "../kirie-platform" }
thiserror = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
arc-swap = { workspace = true }

cef = { version = "149", default-features = false, optional = true }
cef-dll-sys = { workspace = true, optional = true }

libloading = { version = "0.8", optional = true }
gtk = { workspace = true, optional = true }
gtk-layer-shell = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6", optional = true }
block2 = { version = "0.6", optional = true }
objc2-app-kit = { version = "0.3", optional = true, default-features = false, features = ["std", "NSApplication", "NSWindow", "NSView", "NSResponder", "NSImage", "NSImageRep", "NSBitmapImageRep", "NSGraphics", "NSScreen", "NSRunningApplication"] }
objc2-foundation = { version = "0.3", optional = true, default-features = false, features = ["std", "NSDate", "NSRunLoop", "NSString", "NSURL", "NSURLRequest", "NSGeometry", "NSError", "NSData", "NSObjCRuntime"] }
objc2-web-kit = { version = "0.3", optional = true, default-features = false, features = ["std", "block2", "objc2-app-kit", "objc2-core-foundation", "WKWebView", "WKWebViewConfiguration", "WKSnapshotConfiguration", "WKNavigation"] }

[[bin]]
name = "kirie-cef-helper"
path = "src/bin/kirie-cef-helper.rs"
required-features = ["cef"]

[dev-dependencies]
image = { workspace = true }

[[bin]]
name = "kirie-webhost"
path = "src/bin/kirie-webhost.rs"
required-features = ["cef"]

[[bin]]
name = "kirie-webviewhost"
path = "src/bin/kirie-webviewhost.rs"
required-features = ["webview"]
